@extends('layouts.app')

@section('title', 'What I\'m Into')

@push('styles')
    <link rel="stylesheet" href="{{ asset('css/what-im-into.css') }}">
@endpush

@section('content')
<section class="into-page">
    <!-- Header -->
    <div class="into-header">
        <div class="into-badge">
            <i class="fas fa-star"></i> Beyond the Code
        </div>
        <h1 class="into-title">
            What I'm <span class="highlight">Into</span>
        </h1>
        <p class="into-subtitle">
            Drag to explore • Click cards for details
        </p>
    </div>

    <!-- 3D Hologram Stage -->
    <div class="holo-stage">
        <!-- Grid Background -->
        <div class="holo-grid-bg"></div>
        
        <!-- Projection Dots -->
        <div class="projection-dots"></div>
        
        <!-- Data Stream -->
        <div class="data-stream"></div>
        
        <!-- Cards generated by JS -->
    </div>

    <!-- Music Bar -->
    <div class="music-bar">
        <div class="music-bar-cover">
            <img src="{{ asset('images/playlist/baskara.png') }}" alt="Now Playing">
        </div>
        <div class="music-bar-info">
            <div class="music-bar-title">Timeless</div>
            <div class="music-bar-artist">The Weeknd</div>
        </div>
        <div class="music-bar-controls">
            <button class="bar-btn"><i class="fas fa-step-backward"></i></button>
            <button class="bar-btn play-btn"><i class="fas fa-play"></i></button>
            <button class="bar-btn"><i class="fas fa-step-forward"></i></button>
        </div>
    </div>
</section>
@endsection

@push('scripts')
    <script src="{{ asset('js/what-im-into.js') }}"></script>
@endpush