@extends('layouts.app')

@section('title', 'What I\'ve Built')

@section('content')
<section class="projects-page">
    <!-- Header -->
    <div class="projects-header">
        <div class="projects-badge">
            <i class="fas fa-star"></i> Project Galaxy
        </div>
        <h1 class="projects-title">
            What I've <span class="highlight">Built</span>
        </h1>
        <p class="projects-subtitle">
            Drag to explore • Scroll to zoom • Click to discover
        </p>
    </div>

    <!-- Filter Tabs -->
    <div class="filter-tabs">
        <button class="filter-tab active" data-filter="all">
            <span class="filter-dot all"></span> All Projects
        </button>
        <button class="filter-tab" data-filter="personal">
            <span class="filter-dot personal"></span> Personal
        </button>
        <button class="filter-tab" data-filter="freelance">
            <span class="filter-dot freelance"></span> Freelance
        </button>
        <button class="filter-tab" data-filter="certification">
            <span class="filter-dot certification"></span> Certifications
        </button>
    </div>

    <!-- Orrery Container -->
    <div class="orrery-container" id="orreryContainer">
        <!-- Orbit Rings -->
        <div class="orbit-ring inner"></div>
        <div class="orbit-ring middle"></div>
        <div class="orbit-ring outer"></div>
        
        <!-- Central Sun -->
        <div class="central-sun">
            <div class="sun-core"></div>
            <div class="sun-label">MY WORK</div>
        </div>

        <!-- Project Planets (generated by JS) -->
        <div id="planetsContainer"></div>
        
        <!-- Dust Trail Container -->
        <div class="dust-trail" id="dustTrail"></div>
    </div>

    <!-- Zoom Controls -->
    <div class="zoom-controls">
        <button class="zoom-btn" id="zoomIn" title="Zoom In">
            <i class="fas fa-plus"></i>
        </button>
        <button class="zoom-btn" id="zoomOut" title="Zoom Out">
            <i class="fas fa-minus"></i>
        </button>
        <button class="zoom-btn" id="resetView" title="Reset View">
            <i class="fas fa-home"></i>
        </button>
    </div>

    <!-- Hologram Detail Panel -->
    <div class="hologram-panel" id="hologramPanel">
        <button class="hologram-close" id="closeHologram">
            <i class="fas fa-times"></i>
        </button>
        <div class="hologram-image" id="hologramImage">
            <img src="" alt="Project Preview">
        </div>
        <span class="hologram-type" id="hologramType"></span>
        <h3 class="hologram-title" id="hologramTitle"></h3>
        <p class="hologram-desc" id="hologramDesc"></p>
    </div>
</section>
@endsection